---
- name: Postges_install -> Add pgdg repo to sources.list.d
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pgdg.list
    line: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    create: true

# module error
#- name: Postges_install -> Download PostgreSQL key and add it to system keyring 
#  ansible.builtin.apt_key:
#    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
#    state: present

- name: Postges_install -> Download PostgreSQL key and add it to system keyring
  ansible.builtin.shell: curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --batch --yes --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg

- name: Postges_install -> Install PostgreSQL
  ansible.builtin.apt:
    pkg: 
      - postgresql
      - postgresql-client
      - python3-psycopg2
      - iptables-persistent
    state: present
    update_cache: yes
