---
- name: Iptables_config -> Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Iptables_config -> Allow access on for ssh and postgresql port
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item  }}"
    jump: ACCEPT
    source: "{{ external_ip['ansible_facts']['ipify_public_ip'] }}"
  loop:
    - 5432
    - 22

- name: Iptables_config -> Allow all input access for loopback interface
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

#- name: Iptables_config -> Allow access for the dns
#  iptables:
#    chain: INPUT
#    protocol: "{{ item }}"
#    destination_port: 53
#    jump: ACCEPT
#  loop:
#    - tcp
#    - udp

- name: Iptables_config -> Close other connection
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP

- name: Iptables_config ->  Save current state of the firewall in system file
  community.general.iptables_state:
    ip_version: ipv4
    table: filter
    state: saved
    path: /etc/iptables/rules.v4
